### ISSUE TITLE
gives error and delete wite list

### ISSUE THREAD

**Issue by rijinrij** [PushpenderIndia/subdover#4]
┌─[root@parrot]─[/opt/subdover]
└──╼ #ls
env  example_target.txt  externals  img  README.md  requirements.txt  src  subdover.py  version.txt
┌─[root@parrot]─[/opt/subdover]
└──╼ #nano list.txt
┌─[root@parrot]─[/opt/subdover]
└──╼ #ls
env  example_target.txt  externals  img  list.txt  README.md  requirements.txt  src  subdover.py  version.txt
┌─[root@parrot]─[/opt/subdover]
└──╼ #python3 subdover.py -l list.txt
		Author: Pushpender Singh  | GitHub: PushpenderIndia

==================================================================
[*] Adding Appropriate Web Protocal to Subdomains using httpx ...
[*] Writing Subdomains in New TXT file ...
Traceback (most recent call last):
  File "subdover.py", line 240, in <module>
    os.rename(arguments.subdomain_list.replace(filename, filename.replace(" ", "_"))+"-httpx.txt", arguments.subdomain_list.replace(filename, filename.replace(" ", "_")))
FileNotFoundError: [Errno 2] No such file or directory: 'list.txt-httpx.txt' -> 'list.txt'
┌─[✗]─[root@parrot]─[/opt/subdover]
└──╼ #ls
env  example_target.txt  externals  img  README.md  requirements.txt  src  subdover.py  version.txt
┌─[root@parrot]─[/opt/subdover]
└──╼ #

**Comment by PushpenderIndia** [comment]
Please download subdover again, i think this issue has been fixed already.

Download subdover again (not through --update) and confirm whether the
issue is fixed or not

**Comment by rijinrij** [comment]
fixed thanks,
 and error with -d domain.com
[*] Finding Subdomain Using findomain ...
[*] Adding Appropriate Web Protocal to Subdomains using httpx ...
[*] Saving Subdomains in TXT file ...
Traceback (most recent call last):
  File "subdover.py", line 268, in <module>
    enumSubdomain(arguments.domain)          
  File "subdover.py", line 101, in enumSubdomain
    os.remove(f"{domain}.txt")
FileNotFoundError: [Errno 2] No such file or directory: 'google.com.txt'

**Comment by PushpenderIndia** [comment]
Make sure that findomain is installed on your system and is accessible from
any directory,

Install all the dependencies using installer_linux.py, and then try again

Type "findomain" in your terminal without qoutes, if findomain is running
without any issue, then please tell,

Otherwise, it is a issue due to missing dependency

**Comment by PushpenderIndia** [comment]
Download Subdover again, I have added a dependencies checker, so it will check the dependencies every time you run it.

If particular dependency is not installed, it will simply show it to screen and quite.

Kindly download subdover again and check whether the issue you are facing is due to missing dependencies

**Comment by rijinrij** [comment]
thanks for update its fixed
